/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AssociatePanel.java
 *
 * Created on 2012-1-6, 13:58:19
 */
package kd4freebase.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.LayoutStyle.ComponentPlacement;
import kd4freebase.util.PassLog;
import weka.core.Instances;
import weka.gui.explorer.AssociationsPanel;

/**
 *
 * @author Administrator
 */
public class AssociatePanel extends javax.swing.JPanel implements MainFramePanel{

    /** Creates new form AssociatePanel */
    public AssociatePanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        associationsPanel1 = new AssociationsPanel();
        jButton1 = new JButton();

        jButton1.setText("Update");
        jButton1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(477, Short.MAX_VALUE))
            .addComponent(associationsPanel1, GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(associationsPanel1, GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE))
        );
    }//GEN-END:initComponents

    private void jButton1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         if(null==instances){
            PassLog.s(this, "Must query data first");
            return;
        }
        associationsPanel1.setInstances(instances);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public AssociationsPanel associationsPanel1;
    public JButton jButton1;
    // End of variables declaration//GEN-END:variables

    protected MainFrame mainFrame=null;
    protected Instances instances;
    @Override
    public void setMainFrame(MainFrame parent) {
        mainFrame=parent;
    }

    @Override
    public MainFrame getMainFrame() {
        return mainFrame;
    }

    @Override
    public void setInstances(Instances inst) {
        instances=inst;
    }


}
