package kd4freebase.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.JScrollPane;
import javax.swing.LayoutStyle.ComponentPlacement;
import kd4freebase.util.PassLog;
import weka.core.Instances;
import weka.gui.visualize.MatrixPanel;

public class VisualizationPanel extends javax.swing.JPanel implements MainFramePanel {
    private static final long serialVersionUID = 1L;

    public VisualizationPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jButtonUpdate = new JButton();
        jScrollPane1 = new JScrollPane();
        matrixPanel1 = new MatrixPanel();

        jButtonUpdate.setText("Updata");
        jButtonUpdate.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(matrixPanel1);

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonUpdate)
                .addContainerGap(731, Short.MAX_VALUE))
            .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonUpdate)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE))
        );
    }//GEN-END:initComponents

    private void jButtonUpdateActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        if (null == instances) {
            PassLog.s(this, "Must query data first");
            return;
        }
        matrixPanel1.setInstances(instances);
    }//GEN-LAST:event_jButtonUpdateActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public JButton jButtonUpdate;
    public JScrollPane jScrollPane1;
    public MatrixPanel matrixPanel1;
    // End of variables declaration//GEN-END:variables
    protected MainFrame mainFrame = null;
    protected Instances instances;

    @Override
    public void setMainFrame(MainFrame parent) {
        mainFrame = parent;
    }

    @Override
    public MainFrame getMainFrame() {
        return mainFrame;
    }

    @Override
    public void setInstances(Instances inst) {
        instances = inst;
    }
}
